name: Docker build for streamlit app.

on:[push]

jobs:
  build
  
  runs-on: ubuntu-latest
  
  steps:
  - uses: actions/checkout@v2
  - name: docker-build python
    run: |
      docker build ./StreamLitDiabPredictApp -t streamlitapp/pythonDiabpred:1.0
    
  
